### ISSUE TITLE
Perfomance test van oude website

### ISSUE THREAD

**Issue by ArexanK** [ArexanK/INK-back-to-static-site-generation#6]
Doe deze test op jouw localhost en kijk hiervoor in de Dev Tools > Network Tab met een Throttle van bijvoorbeeld Slow 3G.

**Comment by JalalToufik** [comment]
Meet van de homepage van de huidige server side gerenderde webiste de response tijd en het aantal kilobytes dat in de response wordt meegestuurd. Doe deze test op jouw localhost en kijk hiervoor in de Dev Tools > Network Tab met een Throttle van bijvoorbeeld Slow 3G.

**Comment by fatihg61** [comment]
Done shared with team in Teams
